version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.backend
    env_file:
      - ./src/server/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume:/app/src/server/static/

  postgres:
    image: postgres:latest
    env_file:
      - ./src/server/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.backend
    command: celery -A src.server.settings worker -l info
    env_file:
      - ./src/server/.env
    depends_on:
      - postgres
      - redis
      - web

  celery_beat:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.backend
    command: celery -A src.server.settings beat -l info
#    restart: always
    env_file:
      - ./src/server/.env
    depends_on:
      - postgres
      - redis
#      - celery
      - web

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/src/server/static/
    depends_on:
      - web

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    env_file:
#      - ./src/server/.env
#    restart: always
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

volumes:
  pg_data:
  static_volume:
#  pgadmin-data: