# Generated by Django 4.2.5 on 2024-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stop_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='Активированный'),
        ),
    ]
