# Generated by Django 4.2.5 on 2024-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_start_date_remove_user_stop_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_to_send_docs',
            field=models.BooleanField(default=False, verbose_name='Отправка документа на почту'),
        ),
    ]
