# Generated by Django 4.2.5 on 2024-03-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название настройки для поиска')),
                ('search_settings', models.JSONField(verbose_name='JSON с настройками для поиска')),
            ],
            options={
                'verbose_name': 'Настройка поиска',
                'verbose_name_plural': 'Настройки поиска',
                'ordering': ['id'],
            },
        ),
    ]
