# Generated by Django 4.2.5 on 2024-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsingdata',
            name='notice',
            field=models.TextField(default=False, verbose_name='Заметки'),
            preserve_default=False,
        ),
    ]
