# Generated by Django 4.2.5 on 2024-03-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsingdata',
            name='notice',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='parsingdata',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Начальная цена'),
        ),
    ]
